# Generated by Django 5.2.2 on 2025-06-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('training_frequency', models.PositiveIntegerField(help_text='Sessions per week')),
                ('previous_injury', models.CharField(choices=[('none', 'None'), ('calves', 'Calves'), ('hamstrings', 'Hamstrings'), ('quadriceps', 'Quadriceps')], default='none', max_length=50)),
                ('muscle_group', models.CharField(choices=[('calves', 'Calves'), ('hamstrings', 'Hamstrings'), ('quadriceps', 'Quadriceps')], max_length=50)),
                ('contraction_type', models.CharField(choices=[('isometric', 'Isometric'), ('isotonic', 'Isotonic')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(help_text='Raw EMG signal data as a list of values')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emg_data', to='api.userprofile')),
            ],
        ),
    ]
