# Generated by Django 5.2.2 on 2025-06-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_session_emgdata_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='device_id',
            field=models.CharField(blank=True, help_text='Device MAC address or unique ID', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
