# Generated by Django 5.2.2 on 2025-06-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_device_id_session_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emgdata',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
